let indexFooter=[
  {
    name:'首页',
    active_icon:'./image/fsyh.png',
    default_icon:'./image/fsy.png',
    url:'widget://html/index.html'
  },
  {
    name:'七彩生活',
    active_icon:'./image/qcshtbh.png',
    default_icon:'./image/qcshtb.png',
    url:'widget://html/qcsc.html'
  },
  {
    name:'尊享',
    active_icon:'./image/zxtbh.png',
    default_icon:'./image/zxtb.png',
    url:'widget://html/zx.html'
  },
  {
    name:'发圈',
    active_icon:'./image/fqtbh.png',
    default_icon:'./image/fqtb.png',
    url:'widget://html/faq.html'
  },
  {
    name:'我的',
    active_icon:'./image/fwdh.png',
    default_icon:'./image/fwd.png',
    url:'widget://html/wd.html'
  }
];
