let indexFooter=[
  {
    name:'首页',
    active_icon:'./image/fmenu01-dq.png',
    default_icon:'./image/fmenu01.png',
    url:'widget://html/index.html'
  },
  {
    name:'团购',
    active_icon:'./image/fmenu02-dq.png',
    default_icon:'./image/fmenu02.png',
    url:'widget://html/tuangou.html'
  },
  {
    name:'财富',
    active_icon:'./image/fmenu03-dq.png',
    default_icon:'./image/fmenu03.png',
    url:'widget://html/caifu.html'
  },
  {
    name:'交易',
    active_icon:'./image/fmenu04-dq.png',
    default_icon:'./image/fmenu04.png',
    url:'widget://html/jiaoyi.html'
  },
  {
    name:'我的',
    active_icon:'./image/fmenu05-dq.png',
    default_icon:'./image/fmenu05.png',
    url:'widget://html/mine.html'
  }
];
