let indexFooter=[
  {
    name:'首页',
    active_icon:'./image/fsyh.png',
    default_icon:'./image/fsy.png',
    url:'widget://html/index.html'
  },
  {
    name:'七彩生活',
    active_icon:'./image/qcshtbh.png',
    default_icon:'./image/qcshtb.png',
    interface:'interfaceQcsc()'
  },
  {
    name:'健康宝',
    active_icon:'./image/zxtbh.png',
    default_icon:'./image/zxtb.png',
    url:'widget://html/zx.html'
  },
  {
    name:'发圈',
    active_icon:'./image/fqtbh.png',
    default_icon:'./image/fqtb.png',
    url:'widget://html/faq.html'
  },
  {
    name:'我的',
    active_icon:'./image/fwdh.png',
    default_icon:'./image/fwd.png',
    url:'widget://html/wd.html'
  }
];
let iosFooter=[
  {
    name:'首页',
    active_icon:'./image/fsyh.png',
    default_icon:'./image/fsy.png',
    url:'widget://html/sc-index.html'
  },
  {
    name:'分类',
    active_icon:'./image/scflh.png',
    default_icon:'./image/scfl.png',
    url:'widget://html/sc-category.html'
  },
  {
    name:'购物车',
    active_icon:'./image/gwch.png',
    default_icon:'./image/gwc.png',
    url:'widget://html/gwc.html'
  },
  {
    name:'个人中心',
    active_icon:'./image/fwdh.png',
    default_icon:'./image/fwd.png',
    url:'widget://html/hyzx.html'
  }
];
let scFooter=[
  {
    name:'商城首页',
    active_icon:'../image/fsyh.png',
    default_icon:'../image/fsy.png',
    url:'widget://html/sc-index.html'
  },
  {
    name:'分类',
    active_icon:'../image/scflh.png',
    default_icon:'../image/scfl.png',
    url:'widget://html/sc-category.html'
  },
  {
    name:'购物车',
    active_icon:'../image/gwch.png',
    default_icon:'../image/gwc.png',
    url:'widget://html/gwc.html'
  },
  {
    name:'个人中心',
    active_icon:'../image/fwdh.png',
    default_icon:'../image/fwd.png',
    url:'widget://html/hyzx.html'
  }
];
